[package]
name = "vmgr"
version = "0.1.0"
authors = ["ziggoon"]
license = "MIT"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.27.0"
ratatui = "0.26.0"
unicode-width = "0.1.13"
virt = "0.3.1"
